version: "2"
services:
      jackett:
        image: linuxserver/jackett
        container_name: jackett
        environment:
          - PUID=998
          - PGID=100
          - TZ=CONTINENT/CITY
        volumes:
          - /srv/dev-disk-by-uuid-cdf0dd29-18eb-47fb-a26b-9d4164ce249e/Configs/Jackett:/config #SET YOUR HD UUID
          - /srv/dev-disk-by-uuid-cdf0dd29-18eb-47fb-a26b-9d4164ce249e/Torrents:/downloads #SET YOUR HD UUID
        ports:
          - 9117:9117
        restart: unless-stopped
    
      qbittorrentvpn:
          image: markusmcnugen/qbittorrentvpn
          container_name: qbittorrentvpn
          privileged: true   
          environment:
          - VPN_USERNAME=user 
          - VPN_PASSWORD=passs
          - PUID=998
          - PGID=100
          - WEBUI_PORT_ENV=8080
          - INCOMING_PORT_ENV=8999
          - VPN_ENABLED=no #enable if you have VPN provider
          - LAN_NETWORK=192.168.1.0/24 #adjust this to YOUR network settings
          - NAME_SERVERS=1.1.1.1,1.0.0.1 #you can use whatever DNS provider you want
          ports:
          - 8080:8080
          - 8999:8999
          - 8999:8999/udp
          volumes:
          - /srv/dev-disk-by-uuid-cdf0dd29-18eb-47fb-a26b-9d4164ce249e/Configs/QBittorrentVPN:/config #SET YOUR HD UUID
          - /srv/dev-disk-by-uuid-cdf0dd29-18eb-47fb-a26b-9d4164ce249e/Torrents:/downloads #SET YOUR HD UUID
          - /etc/timezone:/etc/timezone:ro #This is for TimeZone
          restart: unless-stopped
    
      sonarr:
          image: linuxserver/sonarr
          container_name: sonarr
          environment:
          - PUID=998
          - PGID=100
          - TZ=CONTINENT/CITY
          - UMASK_SET=022
          volumes:
          - /srv/dev-disk-by-uuid-cdf0dd29-18eb-47fb-a26b-9d4164ce249e/Configs/Sonarr:/config #SET YOUR HD UUID
          - /srv/dev-disk-by-uuid-cdf0dd29-18eb-47fb-a26b-9d4164ce249e/Torrents:/downloads #SET YOUR HD UUID
          ports:
          - 8989:8989
          restart: unless-stopped
      radarr:
          image: linuxserver/radarr
          container_name: radarr
          environment:
          - PUID=998
          - PGID=100
          - TZ=CONTINENT/CITY
          - UMASK_SET=022 #optional
          volumes:
          - /srv/dev-disk-by-uuid-cdf0dd29-18eb-47fb-a26b-9d4164ce249e/Configs/Radarr:/config #SET YOUR HD UUID
          - /srv/dev-disk-by-uuid-cdf0dd29-18eb-47fb-a26b-9d4164ce249e/Movies:/movies #SET YOUR HD UUID
          - /srv/dev-disk-by-uuid-cdf0dd29-18eb-47fb-a26b-9d4164ce249e/Torrents:/downloads #SET YOUR HD UUID
          ports:
          - 7878:7878
          restart: unless-stopped